name: Lotto 6/45 result checker

on:
  schedule:
    - cron: 0 12 * * 0 # every Sunday on 09:00 PM (KST)
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: pip install -r requirements.txt
      - name: Check result
        run: python main.py check lo40
        env:
          DHL_USERID: ${{ secrets.DHL_USERID }}
          DHL_PASSWORD: ${{ secrets.DHL_PASSWORD }}
          DHL_USERID_2: ${{ secrets.DHL_USERID_2 }}
          DHL_PASSWORD_2: ${{ secrets.DHL_PASSWORD_2 }}
          TLG_BOTTOKEN: ${{ secrets.TLG_BOTTOKEN }}
          TLG_CHATID: ${{ secrets.TLG_CHATID }}
